// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRecipeByID(ctx context.Context, id uuid.UUID) (Recipe, error)
	GetRecipes(ctx context.Context, arg GetRecipesParams) ([]Recipe, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
